
#  (c) 2019 John Erps
#  This software is licensed under the MIT license (see LICENSE)


#  Include: Members.


mbr    TOOLSRC     CAFBUILD     REXX    "Compile All Objects"
mbr    TOOLSRC     CAFBUILDT    CLLE    "Compile Tool Objects"
mbr    TOOLSRC     CO           CMD     "Compile Object"
mbr    TOOLSRC     CO0          CLLE    "Compile Object - Cmd Processor"
mbr    TOOLSRC     COCLMOD      CLLE    "CO: CLLE (*MODULE) . . . . . . . . . . . .CRTCLMOD"
mbr    TOOLSRC     COCLPGM      CLLE    "CO: CLP/CLLE (*PGM)  . . . . . . CRTBNDCL/CRTCLPGM"
mbr    TOOLSRC     COCMD        CLLE    "CO: CMD (*CMD) . . . . . . . . . . . . . . .CRTCMD"
mbr    TOOLSRC     CODSPF       CLLE    "CO: DSPF (*FILE) . . . . . . . . . . . . . CRTDSPF"
mbr    TOOLSRC     COPFLF       CLLE    "CO: PF/LF (*FILE)  . . . . CRTPF/CHGPF/CRTLF/CHGLF"
mbr    TOOLSRC     COPSCC       RPGLE   "CO: Process Source Compile Commands"
mbr    TOOLSRC     CORPGMOD     CLLE    "CO: RPGLE (*MODULE)  . . . . . . . . . . CRTRPGMOD"
mbr    TOOLSRC     CORPGPGM     CLLE    "CO: RPG/RPGLE (*PGM) . . . . . CRTBNDRPG/CRTRPGPGM"
mbr    TOOLSRC     RDICO        CMD     "RDi: Compile Object"
mbr    TOOLSRC     RDICO0       CLLE    "RDi: Compile Object - Cmd Processor"
mbr    TOOLSRC     RTVDFTCAFL   CLLE    "Retrieve Default CAF Lib"
mbr    TOOLSRC     SHWDFTCAFL   CLLE    "Show Default CAF Lib"
mbr    TOOLSRC     CAFSRCFRS    CMD     "CAF Source From Streamfile"
mbr    TOOLSRC     CAFSRCFRS0   CLLE    "CAF Source From Streamfile - CP 0"
mbr    TOOLSRC     CAFSRCFRS1   CLLE    "CAF Source From Streamfile - CP 1"
mbr    TOOLSRC     CAFSRCTOS    CMD     "CAF Source To Streamfile"
mbr    TOOLSRC     CAFSRCTOS0   CLLE    "CAF Source To Streamfile - CP 0"
mbr    TOOLSRC     CAFSRCTOS1   CLLE    "CAF Source To Streamfile - CP 1"
mbr    TOOLSRC     CPYCAFDTA    CMD     "Copy CAF Data"
mbr    TOOLSRC     CPYCAFDTA0   CLLE    "Copy CAF Data - CP 0"
mbr    TOOLSRC     SETCAFAUT    CMD     "Set CAF Authorities"
mbr    TOOLSRC     SETCAFAUT0   CLLE    "Set CAF Authorities - CP 0"
mbr    TOOLSRC     SETCAFAUT1   CLLE    "Set CAF Authorities - CP 1"
mbr    TOOLSRC     SETCAFAUT2   CLLE    "Set CAF Authorities - CP 2"
mbr    TOOLSRC     SETCAFAUT3   CLLE    "Set CAF Authorities - CP 3"
mbr    TOOLSRC     SETCAFAUT4   CLLE    "Set CAF Authorities - CP 4"
mbr    TOOLSRC     SETCAFAUT8   RPGLE   "Set CAF Authorities - CP 8"
mbr    TOOLSRC     TIFCAFSRCF   RPGLE   "Test If CAF Sourcefile"
mbr    QINCSRC     PGM_HEAD1    RPGLE   "Program Header specs (ACTGRP *NEW)"
mbr    QINCSRC     PGM_HEAD2    RPGLE   "Program Header specs (ACTGRP *CALLER)"
mbr    QINCSRC     C_ERRNO      RPGLE   "C errno values"
mbr    QINCSRC     CAPPDC_ROE   RPGLE   "Common App SubSys Data Cmd DC: sub return_on_error"
mbr    QINCSRC     CAFMENU      RPGLE   "Prototype for program CAFMENU"
mbr    QINCSRC     CAFMENUG     RPGLE   "Prototype for program CAFMENUG"
mbr    QINCSRC     CAFMENUGD    RPGLE   "Prototype for program CAFMENUGD"
mbr    QINCSRC     CAFNWD       RPGLE   "Prototype for program CAFNWD"
mbr    QINCSRC     CAFNWDT      RPGLE   "Prototype for program CAFNWDT"
mbr    QINCSRC     CAFSQLS      RPGLE   "Prototype for program CAFSQLS"
mbr    QINCSRC     CAFSQLSD     RPGLE   "Prototype for program CAFSQLSD"
mbr    QINCSRC     DPGM_HEAD    RPGLE   "Display Program Header specs"
mbr    QINCSRC     DPGM_LPI     RPGLE   "Display Program Local Procedure Implementations"
mbr    QINCSRC     DPGM_LPP     RPGLE   "Display Program Local Procedure Prototypes"
mbr    QINCSRC     DPGM_SUBR    RPGLE   "Display Program Subroutines"
mbr    QINCSRC     DS_PSI       RPGLE   "Datastructure: Program Status Information"
mbr    QINCSRC     IFSCONST     RPGLE   "IFS API Constants"
mbr    QINCSRC     IFSPROTO     RPGLE   "IFS API Prototypes"
mbr    QDDSSRC     CAFMENU      DSPF    "CAF - Menu"
mbr    QDDSSRC     CAFMENUG     DSPF    "CAF - Menu Groups: Work with"
mbr    QDDSSRC     CAFMENUGD    DSPF    "CAF - Menu Groups: Detail"
mbr    QDDSSRC     CAFNWD       DSPF    "CAF - Non-Workdays"
mbr    QDDSSRC     CAFNWDT      DSPF    "CAF - Non-Workday Types"
mbr    QDDSSRC     CAFSQLS      DSPF    "CAF - SQL Statements: Work with"
mbr    QDDSSRC     CAFSQLSD     DSPF    "CAF - SQL Statements: Detail"
mbr    QRPGLESRC   CAFMENU      RPGLE   "CAF - Menu"
mbr    QRPGLESRC   CAFMENUG     RPGLE   "CAF - Menu Groups: Work with"
mbr    QRPGLESRC   CAFMENUGD    RPGLE   "CAF - Menu Groups: Detail"
mbr    QRPGLESRC   CAFNWD       RPGLE   "CAF - Non-Workdays"
mbr    QRPGLESRC   CAFNWDT      RPGLE   "CAF - Non-Workday Types"
mbr    QRPGLESRC   CAFSQLS      RPGLE   "CAF - SQL Statements: Work with"
mbr    QRPGLESRC   CAFSQLSD     RPGLE   "CAF - SQL Statements: Detail"
mbr    QCLLESRC    CAFMENUG0    CLLE    "CAFMENUG Cmd Processor"
mbr    QCLLESRC    CAFMENU0     CLLE    "CAFMENU Cmd Processor"
mbr    QCLLESRC    CAFNWD0      CLLE    "CAFNWD Cmd Processor"
mbr    QCLLESRC    CAFNWDT0     CLLE    "CAFNWDT Cmd Processor"
mbr    QCLLESRC    CAFSQLS0     CLLE    "CAFSQLS Cmd Processor"
mbr    QCMDSRC     CAFMENU      CMD     "CAF - Menu"
mbr    QCMDSRC     CAFMENUG     CMD     "CAF - Menu Groups: Work with"
mbr    QCMDSRC     CAFNWD       CMD     "CAF - Non-Workdays"
mbr    QCMDSRC     CAFNWDT      CMD     "CAF - Non-Workday Types"
mbr    QCMDSRC     CAFSQLS      CMD     "CAF - SQL Statements: Work with"
mbr    CSYSBASES   CSYS_BASE    BND     "Common System: Base"
mbr    CSYSBASES   CSYSBASEB0   CLLE    "CSYSBASE/Build 0: All"
mbr    CSYSBASES   CSYSBASEB1   CLLE    "CSYSBASE/Build 1: Prereqs"
mbr    CSYSBASES   CSYSBASEB2   CLLE    "CSYSBASE/Build 2: Modules"
mbr    CSYSBASES   CSYSBASEB3   CLLE    "CSYSBASE/Build 3: Serviceprogram"
mbr    CSYSBASES   CSYSBASEB4   CLLE    "CSYSBASE/Build 4: Binding Directory"
mbr    CSYSBASES   CSYSBASEB8   CLLE    "CSYSBASE/Build 8: Other"
mbr    CSYSBASES   CSYSBASEB9   CLLE    "CSYSBASE/Build 9: Clean Up"
mbr    CSYSBASES   CSYSBASECV   RPGLE   "CSYSBASE/Module CV: Conversions"
mbr    CSYSBASES   CSYSBASEDF   RPGLE   "CSYSBASE/Module DF: DisplayFile"
mbr    CSYSBASES   CSYSBASEDT   RPGLE   "CSYSBASE/Module DT: Date/Time functions"
mbr    CSYSBASES   CSYSBASEF0   PF      "CSYSBASE/File 0: SysBase Values"
mbr    CSYSBASES   CSYSBASEF1   PF      "CSYSBASE/File 1: Non-Work Day Types"
mbr    CSYSBASES   CSYSBASEF2   PF      "CSYSBASE/File 2: Non-Work Days"
mbr    CSYSBASES   CSYSBASEP0   RPGLE   "CSYSBASE/Program 0: Initial Data Load"
mbr    CSYSBASES   CSYSBASERM   RPGLE   "CSYSBASE/Module RM: Resource Management"
mbr    CSYSBASES   CSYSBASETU   RPGLE   "CSYSBASE/Module TU: Text Utilities"
mbr    CSYSBASES   CSYSBASEWM   RPGLE   "CSYSBASE/Module WM: Work Management"
mbr    CSYSBASES   CSYSBASEXD   RPGLE   "CSYSBASE/Module XD: XML Document"
mbr    CSYSBASES   CSYSBASEXX   RPGLE   "CSYSBASE/Module XX: Miscellaneous"
mbr    CSYSBASES   INCL__CV     RPGLE   "CSYSBASE/Include: Module CV (Internal)"
mbr    CSYSBASES   INCL__DF     RPGLE   "CSYSBASE/Include: Module DF (Internal)"
mbr    CSYSBASES   INCL__DT     RPGLE   "CSYSBASE/Include: Module DT (Internal)"
mbr    CSYSBASES   INCL__MODD   RPGLE   "CSYSBASE/Include: Module Definitions"
mbr    CSYSBASES   INCL__MODH   RPGLE   "CSYSBASE/Include: Module Header Specs"
mbr    CSYSBASES   INCL__TU     RPGLE   "CSYSBASE/Include: Module TU (Internal)"
mbr    CSYSBASES   INCL__WM     RPGLE   "CSYSBASE/Include: Module WM (Internal)"
mbr    CSYSBASES   INCL__XD     RPGLE   "CSYSBASE/Include: Module XD (Internal)"
mbr    CSYSBASES   INCL__XX     RPGLE   "CSYSBASE/Include: Module XX (Internal)"
mbr    CSYSBASES   INCL_API     RPGLE   "CSYSBASE/Include: API"
mbr    CSYSBASES   INCL_CV      RPGLE   "CSYSBASE/Include: Conversions"
mbr    CSYSBASES   INCL_DEFS    RPGLE   "CSYSBASE/Include: Definitions"
mbr    CSYSBASES   INCL_DF      RPGLE   "CSYSBASE/Include: DisplayFile"
mbr    CSYSBASES   INCL_DT      RPGLE   "CSYSBASE/Include: Date/Time functions"
mbr    CSYSBASES   INCL_RM      RPGLE   "CSYSBASE/Include: Resource Management"
mbr    CSYSBASES   INCL_TU      RPGLE   "CSYSBASE/Include: Text Utilities"
mbr    CSYSBASES   INCL_WM      RPGLE   "CSYSBASE/Include: Work Management"
mbr    CSYSBASES   INCL_XD      RPGLE   "CSYSBASE/Include: XML Document"
mbr    CSYSBASES   INCL_XX      RPGLE   "CSYSBASE/Include: Miscellaneous"
mbr    CSYSSQLSS   CSYS_SQLS    BND     "Common System: SQL Support"
mbr    CSYSSQLSS   CSYSSQLSB0   CLLE    "CSYSSQLS/Build 0: All"
mbr    CSYSSQLSS   CSYSSQLSB1   CLLE    "CSYSSQLS/Build 1: Prereqs"
mbr    CSYSSQLSS   CSYSSQLSB2   CLLE    "CSYSSQLS/Build 2: Modules"
mbr    CSYSSQLSS   CSYSSQLSB3   CLLE    "CSYSSQLS/Build 3: Serviceprogram"
mbr    CSYSSQLSS   CSYSSQLSB4   CLLE    "CSYSSQLS/Build 4: Binding Directory"
mbr    CSYSSQLSS   CSYSSQLSB8   CLLE    "CSYSSQLS/Build 8: Other"
mbr    CSYSSQLSS   CSYSSQLSB9   CLLE    "CSYSSQLS/Build 9: Clean Up"
mbr    CSYSSQLSS   CSYSSQLSCI   RPGLE   "CSYSSQLS/Module CI: Call Interface"
mbr    CSYSSQLSS   CSYSSQLSC1   CMD     "CSYSSQLS/Command 1: Edit SQL Statement"
mbr    CSYSSQLSS   CSYSSQLSFR   PF      "CSYSSQLS/Field Reference File"
mbr    CSYSSQLSS   CSYSSQLSF1   PF      "CSYSSQLS/File 1: SQL Statements"
mbr    CSYSSQLSS   CSYSSQLSP0   RPGLE   "CSYSSQLS/Program 0: Initial Data Load"
mbr    CSYSSQLSS   CSYSSQLSP1   RPGLE   "CSYSSQLS/Program 1: Edit SQL Statement"
mbr    CSYSSQLSS   CSYSSQLSP8   CLLE    "CSYSSQLS/Program 8: Release SP/RCLACTGRP CSYSSQLS"
mbr    CSYSSQLSS   CSYSSQLSP9   RPGLE   "CSYSSQLS/Program 9: Release SP CSYSSQLS"
mbr    CSYSSQLSS   CSYSSQLSRM   RPGLE   "CSYSSQLS/Module RM: Resource Management"
mbr    CSYSSQLSS   CSYSSQLSSS   RPGLE   "CSYSSQLS/Module SS: Statement Storage"
mbr    CSYSSQLSS   INCL__CI     RPGLE   "CSYSSQLS/Include: Module CI (Internal)"
mbr    CSYSSQLSS   INCL__MODD   RPGLE   "CSYSSQLS/Include: Module Definitions"
mbr    CSYSSQLSS   INCL__MODH   RPGLE   "CSYSSQLS/Include: Module Header Specs"
mbr    CSYSSQLSS   INCL__SS     RPGLE   "CSYSSQLS/Include: Module SS (Internal)"
mbr    CSYSSQLSS   INCL_API     RPGLE   "CSYSSQLS/Include: API"
mbr    CSYSSQLSS   INCL_CI      RPGLE   "CSYSSQLS/Include: Call Interface"
mbr    CSYSSQLSS   INCL_DEFS    RPGLE   "CSYSSQLS/Include: Definitions"
mbr    CSYSSQLSS   INCL_RM      RPGLE   "CSYSSQLS/Include: Resource Management"
mbr    CSYSSQLSS   INCL_SS      RPGLE   "CSYSSQLS/Include: Statement Storage"
mbr    CAPPBASES   CAPP_BASE    BND     "Common Application: Base"
mbr    CAPPBASES   CAPPBASEAM   RPGLE   "CAPPBASE/Module AM: Application Messages"
mbr    CAPPBASES   CAPPBASEB0   CLLE    "CAPPBASE/Build 0: All"
mbr    CAPPBASES   CAPPBASEB1   CLLE    "CAPPBASE/Build 1: Prereqs"
mbr    CAPPBASES   CAPPBASEB2   CLLE    "CAPPBASE/Build 2: Modules"
mbr    CAPPBASES   CAPPBASEB3   CLLE    "CAPPBASE/Build 3: Serviceprogram"
mbr    CAPPBASES   CAPPBASEB4   CLLE    "CAPPBASE/Build 4: Binding Directory"
mbr    CAPPBASES   CAPPBASEB8   CLLE    "CAPPBASE/Build 8: Other"
mbr    CAPPBASES   CAPPBASEB9   CLLE    "CAPPBASE/Build 9: Clean Up"
mbr    CAPPBASES   CAPPBASEIR   RPGLE   "CAPPBASE/Module IR: Interpret Raw input"
mbr    CAPPBASES   CAPPBASEMS   RPGLE   "CAPPBASE/Module MS: Message Support"
mbr    CAPPBASES   CAPPBASEPT   RPGLE   "CAPPBASE/Module PT: Presentation Texts"
mbr    CAPPBASES   CAPPBASERM   RPGLE   "CAPPBASE/Module RM: Resource Management"
mbr    CAPPBASES   CAPPBASEVA   RPGLE   "CAPPBASE/Module VA: Value Arrays"
mbr    CAPPBASES   CAPPBASEXX   RPGLE   "CAPPBASE/Module XX: Miscellaneous"
mbr    CAPPBASES   INCL__AM     RPGLE   "CAPPBASE/Include: Module AM (Internal)"
mbr    CAPPBASES   INCL__IR     RPGLE   "CAPPBASE/Include: Module IR (Internal)"
mbr    CAPPBASES   INCL__MODD   RPGLE   "CAPPBASE/Include: Module Definitions"
mbr    CAPPBASES   INCL__MODH   RPGLE   "CAPPBASE/Include: Module Header Specs"
mbr    CAPPBASES   INCL__MS     RPGLE   "CAPPBASE/Include: Module MS (Internal)"
mbr    CAPPBASES   INCL__PT     RPGLE   "CAPPBASE/Include: Module PT (Internal)"
mbr    CAPPBASES   INCL__VA     RPGLE   "CAPPBASE/Include: Module VA (Internal)"
mbr    CAPPBASES   INCL__XX     RPGLE   "CAPPBASE/Include: Module XX (Internal)"
mbr    CAPPBASES   INCL_API     RPGLE   "CAPPBASE/Include: API"
mbr    CAPPBASES   INCL_AM      RPGLE   "CAPPBASE/Include: Application Messages"
mbr    CAPPBASES   INCL_DEFS    RPGLE   "CAPPBASE/Include: Definitions"
mbr    CAPPBASES   INCL_IR      RPGLE   "CAPPBASE/Include: Interpret Raw input"
mbr    CAPPBASES   INCL_MS      RPGLE   "CAPPBASE/Include: Message Support"
mbr    CAPPBASES   INCL_PT      RPGLE   "CAPPBASE/Include: Presentation Texts"
mbr    CAPPBASES   INCL_RM      RPGLE   "CAPPBASE/Include: Resource Management"
mbr    CAPPBASES   INCL_VA      RPGLE   "CAPPBASE/Include: Value Arrays"
mbr    CAPPBASES   INCL_XX      RPGLE   "CAPPBASE/Include: Miscellaneous"
mbr    CAPPSSAMS   CAPP_SSAM    BND     "Common Application: SubSystem AppMenu"
mbr    CAPPSSAMS   CAPPSSAMAM   RPGLE   "CAPPSSAM/Module AM: Application Messages"
mbr    CAPPSSAMS   CAPPSSAMB0   CLLE    "CAPPSSAM/Build 0: All"
mbr    CAPPSSAMS   CAPPSSAMB1   CLLE    "CAPPSSAM/Build 1: Prereqs"
mbr    CAPPSSAMS   CAPPSSAMB2   CLLE    "CAPPSSAM/Build 2: Modules"
mbr    CAPPSSAMS   CAPPSSAMB3   CLLE    "CAPPSSAM/Build 3: Serviceprogram"
mbr    CAPPSSAMS   CAPPSSAMB4   CLLE    "CAPPSSAM/Build 4: Binding Directory"
mbr    CAPPSSAMS   CAPPSSAMB8   CLLE    "CAPPSSAM/Build 8: Other"
mbr    CAPPSSAMS   CAPPSSAMB9   CLLE    "CAPPSSAM/Build 9: Clean Up"
mbr    CAPPSSAMS   CAPPSSAMCH   CLLE    "CAPPSSAM/Command Handler Program"
mbr    CAPPSSAMS   CAPPSSAMDC   RPGLE   "CAPPSSAM/Module DC: Database Commands"
mbr    CAPPSSAMS   CAPPSSAMDQ   RPGLE   "CAPPSSAM/Module DQ: Database Queries"
mbr    CAPPSSAMS   CAPPSSAMFR   PF      "CAPPSSAM/Field Reference File"
mbr    CAPPSSAMS   CAPPSSAMF1   PF      "CAPPSSAM/File 1: Slots"
mbr    CAPPSSAMS   CAPPSSAMF2   PF      "CAPPSSAM/File 2: Slot/Groups"
mbr    CAPPSSAMS   CAPPSSAMF3   PF      "CAPPSSAM/File 3: Groups"
mbr    CAPPSSAMS   CAPPSSAMF4   PF      "CAPPSSAM/File 4: Members/Groups (Group Members)"
mbr    CAPPSSAMS   CAPPSSAMF5   LF      "CAPPSSAM/File 5: Index on CAPPSSAMF2"
mbr    CAPPSSAMS   CAPPSSAMF6   LF      "CAPPSSAM/File 6: Index on CAPPSSAMF4"
mbr    CAPPSSAMS   CAPPSSAMMO   RPGLE   "CAPPSSAM/Module MO: Menu Operations"
mbr    CAPPSSAMS   CAPPSSAMP0   RPGLE   "CAPPSSAM/Program 0: Initial Data Load"
mbr    CAPPSSAMS   CAPPSSAMP1   RPGLE   "CAPPSSAM/Program 1: Add user to group"
mbr    CAPPSSAMS   CAPPSSAMRM   RPGLE   "CAPPSSAM/Module RM: Resource Management"
mbr    CAPPSSAMS   CAPPSSAMVA   RPGLE   "CAPPSSAM/Module VA: Value Arrays"
mbr    CAPPSSAMS   CAPPSSAMXX   RPGLE   "CAPPSSAM/Module XX: Miscellaneous"
mbr    CAPPSSAMS   INCL__AM     RPGLE   "CAPPSSAM/Include: Module AM (Internal)"
mbr    CAPPSSAMS   INCL__DC     RPGLE   "CAPPSSAM/Include: Module DC (Internal)"
mbr    CAPPSSAMS   INCL__DQ     RPGLE   "CAPPSSAM/Include: Module DQ (Internal)"
mbr    CAPPSSAMS   INCL__MO     RPGLE   "CAPPSSAM/Include: Module MO (Internal)"
mbr    CAPPSSAMS   INCL__MODD   RPGLE   "CAPPSSAM/Include: Module Definitions"
mbr    CAPPSSAMS   INCL__MODH   RPGLE   "CAPPSSAM/Include: Module Header Specs"
mbr    CAPPSSAMS   INCL__VA     RPGLE   "CAPPSSAM/Include: Module VA (Internal)"
mbr    CAPPSSAMS   INCL__XX     RPGLE   "CAPPSSAM/Include: Module XX (Internal)"
mbr    CAPPSSAMS   INCL_AM      RPGLE   "CAPPSSAM/Include: Application Messages"
mbr    CAPPSSAMS   INCL_API     RPGLE   "CAPPSSAM/Include: API"
mbr    CAPPSSAMS   INCL_DC      RPGLE   "CAPPSSAM/Include: Database Commands"
mbr    CAPPSSAMS   INCL_DEFS    RPGLE   "CAPPSSAM/Include: Definitions"
mbr    CAPPSSAMS   INCL_DQ      RPGLE   "CAPPSSAM/Include: Database Queries"
mbr    CAPPSSAMS   INCL_MO      RPGLE   "CAPPSSAM/Include: Menu Operations"
mbr    CAPPSSAMS   INCL_RM      RPGLE   "CAPPSSAM/Include: Resource Management"
mbr    CAPPSSAMS   INCL_VA      RPGLE   "CAPPSSAM/Include: Value Arrays"
mbr    CAPPSSAMS   INCL_XX      RPGLE   "CAPPSSAM/Include: Miscellaneous"
mbr    CAPPDISPS   CAPP_DISP    BND     "Common Application: Display"
mbr    CAPPDISPS   CAPPDISPB0   CLLE    "CAPPDISP/Build 0: All"
mbr    CAPPDISPS   CAPPDISPB1   CLLE    "CAPPDISP/Build 1: Prereqs"
mbr    CAPPDISPS   CAPPDISPB2   CLLE    "CAPPDISP/Build 2: Modules"
mbr    CAPPDISPS   CAPPDISPB3   CLLE    "CAPPDISP/Build 3: Serviceprogram"
mbr    CAPPDISPS   CAPPDISPB4   CLLE    "CAPPDISP/Build 4: Binding Directory"
mbr    CAPPDISPS   CAPPDISPB8   CLLE    "CAPPDISP/Build 8: Other"
mbr    CAPPDISPS   CAPPDISPB9   CLLE    "CAPPDISP/Build 9: Clean Up"
mbr    CAPPDISPS   CAPPDISPD1   DSPF    "CAPPDISP/DisplayFile 1: Display Help"
mbr    CAPPDISPS   CAPPDISPD2   DSPF    "CAPPDISP/DisplayFile 2: Select Item"
mbr    CAPPDISPS   CAPPDISPD3   DSPF    "CAPPDISP/DisplayFile 3: Display Messages (*NORMAL)"
mbr    CAPPDISPS   CAPPDISPD4   DSPF    "CAPPDISP/DisplayFile 4: Display Messages (*WIDE)"
mbr    CAPPDISPS   CAPPDISPD9   DSPF    "CAPPDISP/DisplayFile 9: Miscellaneous"
mbr    CAPPDISPS   CAPPDISPF1   PF      "CAPPDISP/File 1: Help Texts"
mbr    CAPPDISPS   CAPPDISPHD   RPGLE   "CAPPDISP/Module HD: Handle Display"
mbr    CAPPDISPS   CAPPDISPP0   RPGLE   "CAPPDISP/Program 0: Initial Data Load"
mbr    CAPPDISPS   CAPPDISPRM   RPGLE   "CAPPDISP/Module RM: Resource Management"
mbr    CAPPDISPS   CAPPDISPSI   RPGLE   "CAPPDISP/Module SI: Select Item"
mbr    CAPPDISPS   CAPPDISPXX   RPGLE   "CAPPDISP/Module XX: Miscellaneous"
mbr    CAPPDISPS   INCL__HD     RPGLE   "CAPPDISP/Include: Module HD (Internal)"
mbr    CAPPDISPS   INCL__MODD   RPGLE   "CAPPDISP/Include: Module Definitions"
mbr    CAPPDISPS   INCL__MODH   RPGLE   "CAPPDISP/Include: Module Header specs"
mbr    CAPPDISPS   INCL__SI     RPGLE   "CAPPDISP/Include: Module SI (Internal)"
mbr    CAPPDISPS   INCL__XX     RPGLE   "CAPPDISP/Include: Module XX (Internal)"
mbr    CAPPDISPS   INCL_API     RPGLE   "CAPPDISP/Include: API"
mbr    CAPPDISPS   INCL_DEFS    RPGLE   "CAPPDISP/Include: Definitions"
mbr    CAPPDISPS   INCL_RM      RPGLE   "CAPPDISP/Include: Resource Management"
mbr    CAPPDISPS   INCL_SI      RPGLE   "CAPPDISP/Include: Select Item"
mbr    CAPPDISPS   INCL_XX      RPGLE   "CAPPDISP/Include: Miscellaneous"
